// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        //Don't use AGP 9.X because it has strict requirements (like mandatory AndroidX migration and manifest changes) that were causing build failures in your legacy com.android.support project.
        agp_version = '8.7.3'
    }
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.10.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
