// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/modules/face_geometry/env_generator_calculator.proto

#include "mediapipe/modules/face_geometry/env_generator_calculator.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace mediapipe {
constexpr FaceGeometryEnvGeneratorCalculatorOptions::FaceGeometryEnvGeneratorCalculatorOptions(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : environment_(nullptr){}
struct FaceGeometryEnvGeneratorCalculatorOptionsDefaultTypeInternal {
  constexpr FaceGeometryEnvGeneratorCalculatorOptionsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FaceGeometryEnvGeneratorCalculatorOptionsDefaultTypeInternal() {}
  union {
    FaceGeometryEnvGeneratorCalculatorOptions _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FaceGeometryEnvGeneratorCalculatorOptionsDefaultTypeInternal _FaceGeometryEnvGeneratorCalculatorOptions_default_instance_;
}  // namespace mediapipe
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto = nullptr;

const uint32_t TableStruct_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions, environment_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, -1, sizeof(::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mediapipe::_FaceGeometryEnvGeneratorCalculatorOptions_default_instance_),
};

const char descriptor_table_protodef_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n>mediapipe/modules/face_geometry/env_ge"
  "nerator_calculator.proto\022\tmediapipe\032,med"
  "iapipe/framework/calculator_options.prot"
  "o\0328mediapipe/modules/face_geometry/proto"
  "s/environment.proto\"\313\001\n)FaceGeometryEnvG"
  "eneratorCalculatorOptions\0229\n\013environment"
  "\030\001 \001(\0132$.mediapipe.face_geometry.Environ"
  "ment2c\n\003ext\022\034.mediapipe.CalculatorOption"
  "s\030\362\331\254\232\001 \001(\01324.mediapipe.FaceGeometryEnvG"
  "eneratorCalculatorOptions"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto_deps[2] = {
  &::descriptor_table_mediapipe_2fframework_2fcalculator_5foptions_2eproto,
  &::descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fprotos_2fenvironment_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto = {
  false, false, 385, descriptor_table_protodef_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto, "mediapipe/modules/face_geometry/env_generator_calculator.proto", 
  &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto_once, descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto_deps, 2, 1,
  schemas, file_default_instances, TableStruct_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto::offsets,
  file_level_metadata_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto, file_level_enum_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto, file_level_service_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto_getter() {
  return &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto(&descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto);
namespace mediapipe {

// ===================================================================

class FaceGeometryEnvGeneratorCalculatorOptions::_Internal {
 public:
  using HasBits = decltype(std::declval<FaceGeometryEnvGeneratorCalculatorOptions>()._has_bits_);
  static const ::mediapipe::face_geometry::Environment& environment(const FaceGeometryEnvGeneratorCalculatorOptions* msg);
  static void set_has_environment(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::mediapipe::face_geometry::Environment&
FaceGeometryEnvGeneratorCalculatorOptions::_Internal::environment(const FaceGeometryEnvGeneratorCalculatorOptions* msg) {
  return *msg->environment_;
}
void FaceGeometryEnvGeneratorCalculatorOptions::clear_environment() {
  if (environment_ != nullptr) environment_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
FaceGeometryEnvGeneratorCalculatorOptions::FaceGeometryEnvGeneratorCalculatorOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
}
FaceGeometryEnvGeneratorCalculatorOptions::FaceGeometryEnvGeneratorCalculatorOptions(const FaceGeometryEnvGeneratorCalculatorOptions& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_environment()) {
    environment_ = new ::mediapipe::face_geometry::Environment(*from.environment_);
  } else {
    environment_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
}

inline void FaceGeometryEnvGeneratorCalculatorOptions::SharedCtor() {
environment_ = nullptr;
}

FaceGeometryEnvGeneratorCalculatorOptions::~FaceGeometryEnvGeneratorCalculatorOptions() {
  // @@protoc_insertion_point(destructor:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void FaceGeometryEnvGeneratorCalculatorOptions::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete environment_;
}

void FaceGeometryEnvGeneratorCalculatorOptions::ArenaDtor(void* object) {
  FaceGeometryEnvGeneratorCalculatorOptions* _this = reinterpret_cast< FaceGeometryEnvGeneratorCalculatorOptions* >(object);
  (void)_this;
}
void FaceGeometryEnvGeneratorCalculatorOptions::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FaceGeometryEnvGeneratorCalculatorOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void FaceGeometryEnvGeneratorCalculatorOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(environment_ != nullptr);
    environment_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FaceGeometryEnvGeneratorCalculatorOptions::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .mediapipe.face_geometry.Environment environment = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_environment(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FaceGeometryEnvGeneratorCalculatorOptions::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .mediapipe.face_geometry.Environment environment = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::environment(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
  return target;
}

size_t FaceGeometryEnvGeneratorCalculatorOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .mediapipe.face_geometry.Environment environment = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *environment_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FaceGeometryEnvGeneratorCalculatorOptions::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    FaceGeometryEnvGeneratorCalculatorOptions::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FaceGeometryEnvGeneratorCalculatorOptions::GetClassData() const { return &_class_data_; }

void FaceGeometryEnvGeneratorCalculatorOptions::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<FaceGeometryEnvGeneratorCalculatorOptions *>(to)->MergeFrom(
      static_cast<const FaceGeometryEnvGeneratorCalculatorOptions &>(from));
}


void FaceGeometryEnvGeneratorCalculatorOptions::MergeFrom(const FaceGeometryEnvGeneratorCalculatorOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_environment()) {
    _internal_mutable_environment()->::mediapipe::face_geometry::Environment::MergeFrom(from._internal_environment());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FaceGeometryEnvGeneratorCalculatorOptions::CopyFrom(const FaceGeometryEnvGeneratorCalculatorOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FaceGeometryEnvGeneratorCalculatorOptions::IsInitialized() const {
  return true;
}

void FaceGeometryEnvGeneratorCalculatorOptions::InternalSwap(FaceGeometryEnvGeneratorCalculatorOptions* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(environment_, other->environment_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FaceGeometryEnvGeneratorCalculatorOptions::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto_getter, &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto_once,
      file_level_metadata_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto[0]);
}
#if !defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912)
const int FaceGeometryEnvGeneratorCalculatorOptions::kExtFieldNumber;
#endif
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::mediapipe::CalculatorOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions >, 11, false >
  FaceGeometryEnvGeneratorCalculatorOptions::ext(kExtFieldNumber, ::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions::default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace mediapipe
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions* Arena::CreateMaybeMessage< ::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
