// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/modules/face_geometry/env_generator_calculator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "mediapipe/framework/calculator_options.pb.h"
#include "mediapipe/modules/face_geometry/protos/environment.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto;
namespace mediapipe {
class FaceGeometryEnvGeneratorCalculatorOptions;
struct FaceGeometryEnvGeneratorCalculatorOptionsDefaultTypeInternal;
extern FaceGeometryEnvGeneratorCalculatorOptionsDefaultTypeInternal _FaceGeometryEnvGeneratorCalculatorOptions_default_instance_;
}  // namespace mediapipe
PROTOBUF_NAMESPACE_OPEN
template<> ::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions* Arena::CreateMaybeMessage<::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mediapipe {

// ===================================================================

class FaceGeometryEnvGeneratorCalculatorOptions final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions) */ {
 public:
  inline FaceGeometryEnvGeneratorCalculatorOptions() : FaceGeometryEnvGeneratorCalculatorOptions(nullptr) {}
  ~FaceGeometryEnvGeneratorCalculatorOptions() override;
  explicit constexpr FaceGeometryEnvGeneratorCalculatorOptions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FaceGeometryEnvGeneratorCalculatorOptions(const FaceGeometryEnvGeneratorCalculatorOptions& from);
  FaceGeometryEnvGeneratorCalculatorOptions(FaceGeometryEnvGeneratorCalculatorOptions&& from) noexcept
    : FaceGeometryEnvGeneratorCalculatorOptions() {
    *this = ::std::move(from);
  }

  inline FaceGeometryEnvGeneratorCalculatorOptions& operator=(const FaceGeometryEnvGeneratorCalculatorOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline FaceGeometryEnvGeneratorCalculatorOptions& operator=(FaceGeometryEnvGeneratorCalculatorOptions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FaceGeometryEnvGeneratorCalculatorOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const FaceGeometryEnvGeneratorCalculatorOptions* internal_default_instance() {
    return reinterpret_cast<const FaceGeometryEnvGeneratorCalculatorOptions*>(
               &_FaceGeometryEnvGeneratorCalculatorOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FaceGeometryEnvGeneratorCalculatorOptions& a, FaceGeometryEnvGeneratorCalculatorOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(FaceGeometryEnvGeneratorCalculatorOptions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FaceGeometryEnvGeneratorCalculatorOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FaceGeometryEnvGeneratorCalculatorOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FaceGeometryEnvGeneratorCalculatorOptions>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FaceGeometryEnvGeneratorCalculatorOptions& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FaceGeometryEnvGeneratorCalculatorOptions& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FaceGeometryEnvGeneratorCalculatorOptions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mediapipe.FaceGeometryEnvGeneratorCalculatorOptions";
  }
  protected:
  explicit FaceGeometryEnvGeneratorCalculatorOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEnvironmentFieldNumber = 1,
  };
  // optional .mediapipe.face_geometry.Environment environment = 1;
  bool has_environment() const;
  private:
  bool _internal_has_environment() const;
  public:
  void clear_environment();
  const ::mediapipe::face_geometry::Environment& environment() const;
  PROTOBUF_NODISCARD ::mediapipe::face_geometry::Environment* release_environment();
  ::mediapipe::face_geometry::Environment* mutable_environment();
  void set_allocated_environment(::mediapipe::face_geometry::Environment* environment);
  private:
  const ::mediapipe::face_geometry::Environment& _internal_environment() const;
  ::mediapipe::face_geometry::Environment* _internal_mutable_environment();
  public:
  void unsafe_arena_set_allocated_environment(
      ::mediapipe::face_geometry::Environment* environment);
  ::mediapipe::face_geometry::Environment* unsafe_arena_release_environment();

  static const int kExtFieldNumber = 323693810;
  static ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::mediapipe::CalculatorOptions,
      ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::mediapipe::FaceGeometryEnvGeneratorCalculatorOptions >, 11, false >
    ext;
  // @@protoc_insertion_point(class_scope:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::mediapipe::face_geometry::Environment* environment_;
  friend struct ::TableStruct_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FaceGeometryEnvGeneratorCalculatorOptions

// optional .mediapipe.face_geometry.Environment environment = 1;
inline bool FaceGeometryEnvGeneratorCalculatorOptions::_internal_has_environment() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || environment_ != nullptr);
  return value;
}
inline bool FaceGeometryEnvGeneratorCalculatorOptions::has_environment() const {
  return _internal_has_environment();
}
inline const ::mediapipe::face_geometry::Environment& FaceGeometryEnvGeneratorCalculatorOptions::_internal_environment() const {
  const ::mediapipe::face_geometry::Environment* p = environment_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::face_geometry::Environment&>(
      ::mediapipe::face_geometry::_Environment_default_instance_);
}
inline const ::mediapipe::face_geometry::Environment& FaceGeometryEnvGeneratorCalculatorOptions::environment() const {
  // @@protoc_insertion_point(field_get:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions.environment)
  return _internal_environment();
}
inline void FaceGeometryEnvGeneratorCalculatorOptions::unsafe_arena_set_allocated_environment(
    ::mediapipe::face_geometry::Environment* environment) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(environment_);
  }
  environment_ = environment;
  if (environment) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions.environment)
}
inline ::mediapipe::face_geometry::Environment* FaceGeometryEnvGeneratorCalculatorOptions::release_environment() {
  _has_bits_[0] &= ~0x00000001u;
  ::mediapipe::face_geometry::Environment* temp = environment_;
  environment_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::face_geometry::Environment* FaceGeometryEnvGeneratorCalculatorOptions::unsafe_arena_release_environment() {
  // @@protoc_insertion_point(field_release:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions.environment)
  _has_bits_[0] &= ~0x00000001u;
  ::mediapipe::face_geometry::Environment* temp = environment_;
  environment_ = nullptr;
  return temp;
}
inline ::mediapipe::face_geometry::Environment* FaceGeometryEnvGeneratorCalculatorOptions::_internal_mutable_environment() {
  _has_bits_[0] |= 0x00000001u;
  if (environment_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::face_geometry::Environment>(GetArenaForAllocation());
    environment_ = p;
  }
  return environment_;
}
inline ::mediapipe::face_geometry::Environment* FaceGeometryEnvGeneratorCalculatorOptions::mutable_environment() {
  ::mediapipe::face_geometry::Environment* _msg = _internal_mutable_environment();
  // @@protoc_insertion_point(field_mutable:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions.environment)
  return _msg;
}
inline void FaceGeometryEnvGeneratorCalculatorOptions::set_allocated_environment(::mediapipe::face_geometry::Environment* environment) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(environment_);
  }
  if (environment) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(environment));
    if (message_arena != submessage_arena) {
      environment = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, environment, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  environment_ = environment;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.FaceGeometryEnvGeneratorCalculatorOptions.environment)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace mediapipe

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fmodules_2fface_5fgeometry_2fenv_5fgenerator_5fcalculator_2eproto
