// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/modules/face_geometry/geometry_pipeline_calculator.proto

#include "mediapipe/modules/face_geometry/geometry_pipeline_calculator.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace mediapipe {
constexpr FaceGeometryPipelineCalculatorOptions::FaceGeometryPipelineCalculatorOptions(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : metadata_path_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct FaceGeometryPipelineCalculatorOptionsDefaultTypeInternal {
  constexpr FaceGeometryPipelineCalculatorOptionsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FaceGeometryPipelineCalculatorOptionsDefaultTypeInternal() {}
  union {
    FaceGeometryPipelineCalculatorOptions _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FaceGeometryPipelineCalculatorOptionsDefaultTypeInternal _FaceGeometryPipelineCalculatorOptions_default_instance_;
}  // namespace mediapipe
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto = nullptr;

const uint32_t TableStruct_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::mediapipe::FaceGeometryPipelineCalculatorOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::mediapipe::FaceGeometryPipelineCalculatorOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mediapipe::FaceGeometryPipelineCalculatorOptions, metadata_path_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, -1, sizeof(::mediapipe::FaceGeometryPipelineCalculatorOptions)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mediapipe::_FaceGeometryPipelineCalculatorOptions_default_instance_),
};

const char descriptor_table_protodef_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\nBmediapipe/modules/face_geometry/geomet"
  "ry_pipeline_calculator.proto\022\tmediapipe\032"
  ",mediapipe/framework/calculator_options."
  "proto\"\237\001\n%FaceGeometryPipelineCalculator"
  "Options\022\025\n\rmetadata_path\030\001 \001(\t2_\n\003ext\022\034."
  "mediapipe.CalculatorOptions\030\364\331\254\232\001 \001(\01320."
  "mediapipe.FaceGeometryPipelineCalculator"
  "Options"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto_deps[1] = {
  &::descriptor_table_mediapipe_2fframework_2fcalculator_5foptions_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto = {
  false, false, 287, descriptor_table_protodef_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto, "mediapipe/modules/face_geometry/geometry_pipeline_calculator.proto", 
  &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto_once, descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto::offsets,
  file_level_metadata_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto, file_level_enum_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto, file_level_service_descriptors_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto_getter() {
  return &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto(&descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto);
namespace mediapipe {

// ===================================================================

class FaceGeometryPipelineCalculatorOptions::_Internal {
 public:
  using HasBits = decltype(std::declval<FaceGeometryPipelineCalculatorOptions>()._has_bits_);
  static void set_has_metadata_path(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

FaceGeometryPipelineCalculatorOptions::FaceGeometryPipelineCalculatorOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:mediapipe.FaceGeometryPipelineCalculatorOptions)
}
FaceGeometryPipelineCalculatorOptions::FaceGeometryPipelineCalculatorOptions(const FaceGeometryPipelineCalculatorOptions& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  metadata_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    metadata_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_metadata_path()) {
    metadata_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_metadata_path(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:mediapipe.FaceGeometryPipelineCalculatorOptions)
}

inline void FaceGeometryPipelineCalculatorOptions::SharedCtor() {
metadata_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  metadata_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FaceGeometryPipelineCalculatorOptions::~FaceGeometryPipelineCalculatorOptions() {
  // @@protoc_insertion_point(destructor:mediapipe.FaceGeometryPipelineCalculatorOptions)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void FaceGeometryPipelineCalculatorOptions::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  metadata_path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void FaceGeometryPipelineCalculatorOptions::ArenaDtor(void* object) {
  FaceGeometryPipelineCalculatorOptions* _this = reinterpret_cast< FaceGeometryPipelineCalculatorOptions* >(object);
  (void)_this;
}
void FaceGeometryPipelineCalculatorOptions::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FaceGeometryPipelineCalculatorOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void FaceGeometryPipelineCalculatorOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:mediapipe.FaceGeometryPipelineCalculatorOptions)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    metadata_path_.ClearNonDefaultToEmpty();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FaceGeometryPipelineCalculatorOptions::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string metadata_path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_metadata_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "mediapipe.FaceGeometryPipelineCalculatorOptions.metadata_path");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FaceGeometryPipelineCalculatorOptions::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mediapipe.FaceGeometryPipelineCalculatorOptions)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string metadata_path = 1;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_metadata_path().data(), static_cast<int>(this->_internal_metadata_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "mediapipe.FaceGeometryPipelineCalculatorOptions.metadata_path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_metadata_path(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mediapipe.FaceGeometryPipelineCalculatorOptions)
  return target;
}

size_t FaceGeometryPipelineCalculatorOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mediapipe.FaceGeometryPipelineCalculatorOptions)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string metadata_path = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_metadata_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FaceGeometryPipelineCalculatorOptions::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    FaceGeometryPipelineCalculatorOptions::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FaceGeometryPipelineCalculatorOptions::GetClassData() const { return &_class_data_; }

void FaceGeometryPipelineCalculatorOptions::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<FaceGeometryPipelineCalculatorOptions *>(to)->MergeFrom(
      static_cast<const FaceGeometryPipelineCalculatorOptions &>(from));
}


void FaceGeometryPipelineCalculatorOptions::MergeFrom(const FaceGeometryPipelineCalculatorOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mediapipe.FaceGeometryPipelineCalculatorOptions)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_metadata_path()) {
    _internal_set_metadata_path(from._internal_metadata_path());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FaceGeometryPipelineCalculatorOptions::CopyFrom(const FaceGeometryPipelineCalculatorOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mediapipe.FaceGeometryPipelineCalculatorOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FaceGeometryPipelineCalculatorOptions::IsInitialized() const {
  return true;
}

void FaceGeometryPipelineCalculatorOptions::InternalSwap(FaceGeometryPipelineCalculatorOptions* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &metadata_path_, lhs_arena,
      &other->metadata_path_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata FaceGeometryPipelineCalculatorOptions::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto_getter, &descriptor_table_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto_once,
      file_level_metadata_mediapipe_2fmodules_2fface_5fgeometry_2fgeometry_5fpipeline_5fcalculator_2eproto[0]);
}
#if !defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912)
const int FaceGeometryPipelineCalculatorOptions::kExtFieldNumber;
#endif
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::mediapipe::CalculatorOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::mediapipe::FaceGeometryPipelineCalculatorOptions >, 11, false >
  FaceGeometryPipelineCalculatorOptions::ext(kExtFieldNumber, ::mediapipe::FaceGeometryPipelineCalculatorOptions::default_instance());

// @@protoc_insertion_point(namespace_scope)
}  // namespace mediapipe
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mediapipe::FaceGeometryPipelineCalculatorOptions* Arena::CreateMaybeMessage< ::mediapipe::FaceGeometryPipelineCalculatorOptions >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mediapipe::FaceGeometryPipelineCalculatorOptions >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
